# Generated by Django 2.1.5 on 2019-02-18 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad_Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=10)),
                ('segundo_nombre', models.CharField(max_length=10)),
                ('apellido_paterno', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud', models.TextField()),
                ('fecha_reserva', models.DateField(auto_now_add=True)),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crudreservas.Medico')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=10)),
                ('segundo_nombre', models.CharField(max_length=10)),
                ('apellido_paterno', models.CharField(max_length=10)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bebe', models.CharField(max_length=10)),
                ('niño', models.CharField(max_length=10)),
                ('adulto', models.CharField(max_length=10)),
                ('tercera_edad', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crudreservas.UsuarioRol'),
        ),
        migrations.AddField(
            model_name='medico',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crudreservas.Usuario'),
        ),
    ]
