# Generated by Django 2.1.5 on 2019-02-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudreservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariorol',
            name='adulto',
        ),
        migrations.RemoveField(
            model_name='usuariorol',
            name='bebe',
        ),
        migrations.RemoveField(
            model_name='usuariorol',
            name='niño',
        ),
        migrations.RemoveField(
            model_name='usuariorol',
            name='tercera_edad',
        ),
        migrations.AddField(
            model_name='usuariorol',
            name='tipo_de_persona',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='usuariorol',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
