# Generated by Django 2.1.5 on 2019-02-19 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudreservas', '0002_auto_20190219_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='crudreservas.UsuarioRol'),
        ),
    ]
