# Generated by Django 2.1.5 on 2019-02-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudreservas', '0003_auto_20190219_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_identificaicon',
            field=models.CharField(choices=[('Cedula', 'Cedula De Ciudadania'), ('Cedula Extranjeria', 'Cedula De Extranjeria'), ('Tarjeta De Identidad', 'Tarjeta De Identidad')], default='Tarjeta De Identidad', max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='apellido_paterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='primer_nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='segundo_nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primer_nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='segundo_nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2),
        ),
    ]
