# Generated by Django 2.1.5 on 2019-02-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudreservas', '0004_auto_20190221_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellido_paterno',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='primer_nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
