# Generated by Django 2.1.5 on 2019-02-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudreservas', '0007_auto_20190221_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(max_length=10),
        ),
    ]
