# Generated by Django 2.1.5 on 2019-02-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudreservas', '0009_auto_20190221_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='primer_nombre',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='segundo_nombre',
            new_name='nombres',
        ),
    ]
